# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Python 3.13 slim base image
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY main.py .

# Install dependencies
RUN pip install --no-cache-dir httpx>=0.28.1 mcp[cli]>=1.4.1

# Expose port if needed (FastMCP defaults to stdio, no port required)

# Default command to run the MCP server
CMD ["python", "main.py"]
